Repository KillahPotatoes/KP-Liberation, pull requests merged in 2020-04, with the labels that each got.

#726 Build tool auto upload 0.97
  .gitignore
  tools/buildtool/README.md
  tools/buildtool/_presets.json
  tools/buildtool/gulpfile.ts
  tools/buildtool/src/Config.ts
  tools/buildtool/src/KpSteam.ts
  tools/buildtool/src/index.ts
  tools/buildtool/tsconfig.json
Labels: enhancement

#737 0.96.7 Locality change of slingloaded cargo
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_addRopeAttachEh.sqf
  Missionframework/functions/fn_getOpforSpawnPoint.sqf
  Missionframework/kp_objectInits.sqf
  Missionframework/scripts/server/base/huron_manager.sqf
  Missionframework/scripts/server/base/startvehicle_spawn.sqf
  README.md
Labels: enhancement

#738 0.96.7 Use structured text for diag_log
  Missionframework/functions/fn_checkClass.sqf
  Missionframework/functions/fn_checkGear.sqf
  Missionframework/functions/fn_crAddAceAction.sqf
  Missionframework/functions/fn_crGlobalMsg.sqf
  Missionframework/functions/fn_getOpforSpawnPoint.sqf
  Missionframework/functions/fn_getSaveableParam.sqf
  Missionframework/functions/fn_sortStorage.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/scripts/client/asymmetric/asymm_notifications.sqf
  Missionframework/scripts/client/civinformant/civinfo_escort.sqf
  Missionframework/scripts/client/civinformant/civinfo_notifications.sqf
  Missionframework/scripts/client/civrep/kp_cr_checkVehicle.sqf
  Missionframework/scripts/client/remotecall/remote_call_intel.sqf
  Missionframework/scripts/server/asymmetric/asymmetric_loop.sqf
  Missionframework/scripts/server/asymmetric/convoy/logistic_convoy_ambush.sqf
  Missionframework/scripts/server/asymmetric/ied/manage_asymIED.sqf
  Missionframework/scripts/server/asymmetric/init_module.sqf
  Missionframework/scripts/server/asymmetric/random/asym_sector_ambush.sqf
  Missionframework/scripts/server/asymmetric/random/sector_guerilla.sqf
  Missionframework/scripts/server/civinformant/civinfo_loop.sqf
  Missionframework/scripts/server/civinformant/init_module.sqf
  Missionframework/scripts/server/civinformant/tasks/civinfo_task.sqf
  Missionframework/scripts/server/civrep/fnc/f_kp_cr_changeCR.sqf
  Missionframework/scripts/server/civrep/fnc/f_kp_cr_getBuildings.sqf
  Missionframework/scripts/server/civrep/fnc/f_kp_cr_liberatedSector.sqf
  Missionframework/scripts/server/civrep/init_buildings.sqf
  Missionframework/scripts/server/civrep/init_module.sqf
  Missionframework/scripts/server/civrep/wounded/civrep_wounded_civs.sqf
  Missionframework/scripts/server/game/manage_weather.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  Missionframework/scripts/server/game/server_restart.sqf
  Missionframework/scripts/server/offloading/group_diag.sqf
  Missionframework/scripts/server/remotecall/add_logiTruck_remote_call.sqf
  Missionframework/scripts/server/remotecall/build_fac_remote_call.sqf
  Missionframework/scripts/server/remotecall/build_remote_call.sqf
  Missionframework/scripts/server/remotecall/start_secondary_remote_call.sqf
  Missionframework/scripts/server/resources/manage_logistics.sqf
  Missionframework/scripts/server/resources/manage_resources.sqf
  Missionframework/scripts/server/resources/recalculate_resources.sqf
  Missionframework/scripts/server/secondary/convoy_hijack.sqf
  Missionframework/scripts/server/secondary/fob_hunting.sqf
  Missionframework/scripts/server/secondary/search_and_rescue.sqf
  Missionframework/scripts/server/sector/ied_manager.sqf
  Missionframework/scripts/server/sector/manage_one_sector.sqf
  Missionframework/scripts/server/sector/manage_sectors.sqf
  Missionframework/scripts/server/sector/wait_to_spawn_sector.sqf
  Missionframework/scripts/shared/defines.hpp
  Missionframework/scripts/shared/diagnostics.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/scripts/shared/kill_manager.sqf
  README.md
Labels: enhancement

#739 0.96.7 Basic Discord Rich Presence
  Missionframework/CfgFunctions.hpp
  Missionframework/description.ext
  Missionframework/functions/fn_setDiscordState.sqf
  Missionframework/init.sqf
  Missionframework/scripts/client/ui/ui_manager.sqf
  README.md
Labels: enhancement

#736 V0.96.7 player menu
  LICENSE.md
  Missionframework/KP/KPGUI/KPGUI_classes.hpp
  Missionframework/KP/KPGUI/KPGUI_defines.hpp
  Missionframework/KP/KPGUI/res/kp512_CA.paa
  Missionframework/KP/KPPLM/KPPLM_functions.hpp
  Missionframework/KP/KPPLM/fnc/fn_apply.sqf
  Missionframework/KP/KPPLM/fnc/fn_create.sqf
  Missionframework/KP/KPPLM/fnc/fn_getInOut.sqf
  Missionframework/KP/KPPLM/fnc/fn_join.sqf
  Missionframework/KP/KPPLM/fnc/fn_openDialog.sqf
  Missionframework/KP/KPPLM/fnc/fn_postInit.sqf
  Missionframework/KP/KPPLM/fnc/fn_preInit.sqf
  Missionframework/KP/KPPLM/fnc/fn_rename.sqf
  Missionframework/KP/KPPLM/fnc/fn_save.sqf
  Missionframework/KP/KPPLM/fnc/fn_showRankData.sqf
  Missionframework/KP/KPPLM/ui/KPPLM_dialog.hpp
  Missionframework/KP/LICENSE
  Missionframework/description.ext
  Missionframework/functions/fn_hasPermission.sqf
  Missionframework/init.sqf
  Missionframework/scripts/client/misc/init_arsenal.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
  README.md
Labels: enhancement

#740 0.96.7 Confirmation dialog for create clearance
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_createClearance.sqf
  Missionframework/functions/fn_createClearanceConfirm.sqf
  Missionframework/scripts/client/actions/action_manager.sqf
  Missionframework/stringtable.xml
  README.md
Labels: enhancement

#742 0.96.7 Zeus placed objects and enemy vehicle capture handling
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_cleanOpforVehicle.sqf
  Missionframework/functions/fn_handlePlacedZeusObject.sqf
  Missionframework/functions/fn_setVehicleCaptured.sqf
  Missionframework/functions/fn_spawnVehicle.sqf
  Missionframework/init.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/scripts/server/game/capture_vehicles.sqf
  Missionframework/scripts/server/game/zeus_synchro.sqf
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
  README.md
Labels: enhancement

#741 Save Manager improvements
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_doSave.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/init.sqf
  Missionframework/scripts/server/game/periodic_save.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/server/remotecall/build_fob_remote_call.sqf
  Missionframework/scripts/server/remotecall/sector_liberated_remote_call.sqf
  Missionframework/scripts/server/secondary/convoy_hijack.sqf
  Missionframework/scripts/server/secondary/fob_hunting.sqf
  Missionframework/scripts/server/sector/attack_in_progress_fob.sqf
  Missionframework/scripts/server/sector/attack_in_progress_sector.sqf
  README.md
Labels: enhancement

#743 0.96.7 Manage actions via a playerNamespace
  Missionframework/CfgFunctions.hpp
  Missionframework/KP/KPPLM/fnc/fn_postInit.sqf
  Missionframework/KP/KPPLM/fnc/fn_preInit.sqf
  Missionframework/functions/fn_addActionsFob.sqf
  Missionframework/functions/fn_addActionsPlayer.sqf
  Missionframework/functions/fn_checkGear.sqf
  Missionframework/functions/fn_checkWeaponCargo.sqf
  Missionframework/functions/fn_doSave.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/kp_objectInits.sqf
  Missionframework/onPlayerRespawn.sqf
  Missionframework/scripts/client/actions/action_manager.sqf
  Missionframework/scripts/client/actions/do_repackage_fob.sqf
  Missionframework/scripts/client/actions/intel_manager.sqf
  Missionframework/scripts/client/actions/recycle_manager.sqf
  Missionframework/scripts/client/actions/unflip_manager.sqf
  Missionframework/scripts/client/build/do_build.sqf
  Missionframework/scripts/client/build/do_build_fob.sqf
  Missionframework/scripts/client/build/do_sector_build.sqf
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/client/misc/playerNamespace.sqf
  Missionframework/scripts/server/base/startgame.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  README.md
Labels: bugfix, enhancement

#745 0.96.7 Discord Update to playerNamespace
  Missionframework/functions/fn_setDiscordState.sqf
  Missionframework/scripts/client/misc/playerNamespace.sqf
  Missionframework/scripts/client/ui/ui_manager.sqf
Labels: enhancement

#744 0.96.7 Logging function
  Missionframework/CfgFunctions.hpp
  Missionframework/KP/KPPLM/fnc/fn_postInit.sqf
  Missionframework/KP/KPPLM/fnc/fn_preInit.sqf
  Missionframework/functions/fn_checkClass.sqf
  Missionframework/functions/fn_checkGear.sqf
  Missionframework/functions/fn_crAddAceAction.sqf
  Missionframework/functions/fn_crGlobalMsg.sqf
  Missionframework/functions/fn_doSave.sqf
  Missionframework/functions/fn_getOpforSpawnPoint.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/functions/fn_getSaveableParam.sqf
  Missionframework/functions/fn_log.sqf
  Missionframework/functions/fn_sortStorage.sqf
  Missionframework/kp_liberation_config.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/scripts/client/asymmetric/asymm_notifications.sqf
  Missionframework/scripts/client/civinformant/civinfo_escort.sqf
  Missionframework/scripts/client/civinformant/civinfo_notifications.sqf
  Missionframework/scripts/client/civrep/kp_cr_checkVehicle.sqf
  Missionframework/scripts/client/remotecall/remote_call_intel.sqf
  Missionframework/scripts/server/asymmetric/asymmetric_loop.sqf
  Missionframework/scripts/server/asymmetric/convoy/logistic_convoy_ambush.sqf
  Missionframework/scripts/server/asymmetric/ied/manage_asymIED.sqf
  Missionframework/scripts/server/asymmetric/init_module.sqf
  Missionframework/scripts/server/asymmetric/random/asym_sector_ambush.sqf
  Missionframework/scripts/server/asymmetric/random/sector_guerilla.sqf
  Missionframework/scripts/server/civinformant/civinfo_loop.sqf
  Missionframework/scripts/server/civinformant/init_module.sqf
  Missionframework/scripts/server/civinformant/tasks/civinfo_task.sqf
  Missionframework/scripts/server/civrep/fnc/f_kp_cr_changeCR.sqf
  Missionframework/scripts/server/civrep/fnc/f_kp_cr_getBuildings.sqf
  Missionframework/scripts/server/civrep/fnc/f_kp_cr_liberatedSector.sqf
  Missionframework/scripts/server/civrep/init_buildings.sqf
  Missionframework/scripts/server/civrep/init_module.sqf
  Missionframework/scripts/server/civrep/wounded/civrep_wounded_civs.sqf
  Missionframework/scripts/server/game/check_victory_conditions.sqf
  Missionframework/scripts/server/game/cleanup_vehicles.sqf
  Missionframework/scripts/server/game/manage_weather.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  Missionframework/scripts/server/game/server_restart.sqf
  Missionframework/scripts/server/offloading/group_diag.sqf
  Missionframework/scripts/server/remotecall/add_logiTruck_remote_call.sqf
  Missionframework/scripts/server/remotecall/build_fac_remote_call.sqf
  Missionframework/scripts/server/remotecall/build_remote_call.sqf
  Missionframework/scripts/server/remotecall/start_secondary_remote_call.sqf
  Missionframework/scripts/server/resources/manage_logistics.sqf
  Missionframework/scripts/server/resources/manage_resources.sqf
  Missionframework/scripts/server/resources/recalculate_resources.sqf
  Missionframework/scripts/server/secondary/convoy_hijack.sqf
  Missionframework/scripts/server/secondary/fob_hunting.sqf
  Missionframework/scripts/server/secondary/search_and_rescue.sqf
  Missionframework/scripts/server/sector/ied_manager.sqf
  Missionframework/scripts/server/sector/manage_one_sector.sqf
  Missionframework/scripts/server/sector/manage_sectors.sqf
  Missionframework/scripts/server/sector/wait_to_spawn_sector.sqf
  Missionframework/scripts/shared/defines.hpp
  Missionframework/scripts/shared/diagnostics.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/scripts/shared/kill_manager.sqf
Labels: enhancement

#746 0.96.7 Arsenal initialization optimized
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_crawlAllItems.sqf
  Missionframework/functions/fn_getVirtualCargo.sqf
  Missionframework/scripts/client/misc/init_arsenal.sqf
  README.md
Labels: enhancement

#747 0.96.7 Replaced the manage_sectors loop with a FSM
  Missionframework/CfgFunctions.hpp
  Missionframework/scripts/server/CfgFunctions.hpp
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/server/sector/fn_sectorMonitor.fsm
  Missionframework/scripts/server/sector/manage_one_sector.sqf
  Missionframework/scripts/server/sector/manage_sectors.sqf
  README.md
Labels: enhancement

#750 0.96.7 A3 High Command
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/server/CfgFunctions.hpp
  Missionframework/scripts/server/highcommand/fn_highcommand.fsm
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
  README.md
Labels: enhancement

#751 0.96.7 capture vehicle tweaks
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_cleanOpforVehicle.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/functions/fn_setVehicleCaptured.sqf
  Missionframework/functions/fn_setVehicleSeized.sqf
  Missionframework/functions/fn_spawnVehicle.sqf
  Missionframework/scripts/client/civrep/kp_cr_checkVehicle.sqf
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  Missionframework/scripts/server/game/zeus_synchro.sqf
  README.md
Labels: bugfix, enhancement

#754 0.96.7 dedicated test tweaks
  Missionframework/scripts/server/highcommand/fn_highcommand.fsm
  Missionframework/scripts/server/sector/fn_sectorMonitor.fsm
Labels: bugfix

#753 0.96.7 Range adjustments
  .gitignore
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/scripts/client/actions/do_recycle.sqf
  Missionframework/scripts/client/build/do_build.sqf
  Missionframework/scripts/client/build/do_sector_build.sqf
  Missionframework/scripts/client/misc/playerNamespace.sqf
  Missionframework/scripts/server/game/cleanup_vehicles.sqf
  Missionframework/scripts/server/remotecall/add_logiTruck_remote_call.sqf
  Missionframework/scripts/server/remotecall/build_fac_remote_call.sqf
  Missionframework/scripts/server/remotecall/del_logiTruck_remote_call.sqf
  Missionframework/scripts/server/resources/manage_logistics.sqf
  Missionframework/scripts/server/resources/manage_resources.sqf
  Missionframework/scripts/server/resources/recalculate_resources.sqf
  README.md
Labels: enhancement

#758 0.96.7 Changed array names in presets init
  Missionframework/functions/fn_crateFromStorage.sqf
  Missionframework/functions/fn_createCrate.sqf
  Missionframework/functions/fn_getGroupType.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/functions/fn_getSquadComp.sqf
  Missionframework/functions/fn_handlePlacedZeusObject.sqf
  Missionframework/functions/fn_setVehicleCaptured.sqf
  Missionframework/kp_liberation_config.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/scripts/client/actions/do_recycle.sqf
  Missionframework/scripts/client/actions/intel_manager.sqf
  Missionframework/scripts/client/actions/recycle_manager.sqf
  Missionframework/scripts/client/ammoboxes/ammobox_action_manager.sqf
  Missionframework/scripts/client/ammoboxes/do_load_box.sqf
  Missionframework/scripts/client/ammoboxes/do_unload_truck.sqf
  Missionframework/scripts/client/build/do_build.sqf
  Missionframework/scripts/client/build/open_build_menu.sqf
  Missionframework/scripts/client/markers/empty_vehicles_marker.sqf
  Missionframework/scripts/client/misc/vehicle_permissions.sqf
  Missionframework/scripts/client/remotecall/remote_call_prisonner.sqf
  Missionframework/scripts/client/ui/squad_management.sqf
  Missionframework/scripts/server/base/startgame.sqf
  Missionframework/scripts/server/game/cleanup_vehicles.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  Missionframework/scripts/server/game/zeus_synchro.sqf
  Missionframework/scripts/server/resources/unit_cap.sqf
  Missionframework/scripts/server/secondary/convoy_hijack.sqf
  Missionframework/scripts/server/secondary/search_and_rescue.sqf
  Missionframework/scripts/server/sector/manage_captureboxes.sqf
  Missionframework/scripts/server/sector/manage_intel.sqf
  Missionframework/scripts/shared/kill_manager.sqf
  README.md
Labels: enhancement

#759 0.96.7 Fixed issues due to `toLower` usage in presets
  Missionframework/functions/fn_crateFromStorage.sqf
  Missionframework/functions/fn_createCrate.sqf
  Missionframework/functions/fn_getGroupType.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/functions/fn_handlePlacedZeusObject.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/scripts/client/actions/do_recycle.sqf
  Missionframework/scripts/client/actions/recycle_manager.sqf
  Missionframework/scripts/client/build/do_build.sqf
  Missionframework/scripts/client/build/open_build_menu.sqf
  Missionframework/scripts/client/markers/empty_vehicles_marker.sqf
  Missionframework/scripts/client/misc/vehicle_permissions.sqf
  Missionframework/scripts/client/remotecall/remote_call_prisonner.sqf
  Missionframework/scripts/server/game/cleanup_vehicles.sqf
  Missionframework/scripts/server/game/zeus_synchro.sqf
  Missionframework/scripts/server/resources/unit_cap.sqf
Labels: bugfix

#755 0.96.7 BIS Support modules for artillery
  Missionframework/functions/fn_crateFromStorage.sqf
  Missionframework/functions/fn_createCrate.sqf
  Missionframework/functions/fn_getGroupType.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/functions/fn_handlePlacedZeusObject.sqf
  Missionframework/kp_liberation_config.sqf
  Missionframework/kp_objectInits.sqf
  Missionframework/onPlayerRespawn.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/scripts/client/actions/do_recycle.sqf
  Missionframework/scripts/client/actions/recycle_manager.sqf
  Missionframework/scripts/client/build/do_build.sqf
  Missionframework/scripts/client/build/open_build_menu.sqf
  Missionframework/scripts/client/markers/empty_vehicles_marker.sqf
  Missionframework/scripts/client/misc/vehicle_permissions.sqf
  Missionframework/scripts/client/remotecall/remote_call_prisonner.sqf
  Missionframework/scripts/server/CfgFunctions.hpp
  Missionframework/scripts/server/game/cleanup_vehicles.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  Missionframework/scripts/server/game/zeus_synchro.sqf
  Missionframework/scripts/server/highcommand/fn_highcommand.fsm
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/server/resources/unit_cap.sqf
  Missionframework/scripts/server/support/fn_createSuppModules.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
  README.md
Labels: enhancement

#760 0.96.7 Further small additions
  Missionframework/GREUH/UI/GREUH_interface.hpp
  Missionframework/KP/KPGUI/KPGUI_classes.hpp
  Missionframework/KP/KPGUI/KPGUI_defines.hpp
  Missionframework/KP/KPPLM/ui/KPPLM_dialog.hpp
  Missionframework/description.ext
  Missionframework/functions/fn_setVehicleCaptured.sqf
  Missionframework/functions/fn_setVehicleSeized.sqf
  Missionframework/functions/fn_spawnVehicle.sqf
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/client/spawn/redeploy_manager.sqf
  Missionframework/scripts/server/battlegroup/random_battlegroups.sqf
  Missionframework/scripts/server/battlegroup/spawn_air.sqf
  Missionframework/scripts/server/battlegroup/spawn_battlegroup.sqf
  Missionframework/scripts/server/patrols/manage_one_patrol.sqf
  Missionframework/scripts/server/patrols/send_paratroopers.sqf
  Missionframework/scripts/server/remotecall/sector_liberated_remote_call.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/defines.hpp
  Missionframework/ui/mission_params.hpp
  README.md
Labels: enhancement

#733 0.96.7 CUP Presets Update #2
  Missionframework/kp_liberation_config.sqf
  Missionframework/presets/blufor/CUP_ACR_Desert.sqf
  Missionframework/presets/blufor/CUP_ACR_Woodland.sqf
  Missionframework/presets/blufor/CUP_BAF_Desert.sqf
  Missionframework/presets/blufor/CUP_BAF_Woodland.sqf
  Missionframework/presets/blufor/CUP_CDF.sqf
  Missionframework/presets/blufor/CUP_ChDKZ.sqf
  Missionframework/presets/blufor/CUP_SLA.sqf
  Missionframework/presets/blufor/CUP_TakiArmy.sqf
  Missionframework/presets/blufor/CUP_USA_Desert.sqf
  Missionframework/presets/blufor/CUP_USA_Woodland.sqf
  Missionframework/presets/blufor/CUP_USMC_Desert.sqf
  Missionframework/presets/blufor/CUP_USMC_Woodland.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/presets/opfor/CUP_AFRF_MSV.sqf
  Missionframework/presets/opfor/CUP_AFRF_ModernMSV.sqf
  Missionframework/presets/opfor/CUP_BAF_Desert.sqf
  Missionframework/presets/opfor/CUP_BAF_Woodland.sqf
  Missionframework/presets/opfor/CUP_CDF.sqf
  Missionframework/presets/opfor/CUP_ChDKZ.sqf
  Missionframework/presets/opfor/CUP_SLA.sqf
  Missionframework/presets/opfor/CUP_TakiArmy.sqf
  Missionframework/presets/resistance/CUP_TakiLocals.sqf
Labels: enhancement

#762 V.0.96.7 Spanish Translation
  Missionframework/stringtable.xml
  README.md
Labels: enhancement

#761 0.96.7 Some fixes after dedicated testing
  CHANGELOG.md
  Missionframework/functions/fn_addActionsPlayer.sqf
  Missionframework/scripts/client/actions/intel_manager.sqf
  Missionframework/scripts/client/actions/redeploy.sqf
  Missionframework/scripts/client/actions/unflip_manager.sqf
  Missionframework/scripts/server/sector/manage_one_sector.sqf
  Missionframework/scripts/shared/diagnostics.sqf
  Missionframework/ui/mission_params.hpp
  README.md
Labels: bugfix

#763 0.96.7 More tweaks
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_addObjectInit.sqf
  Missionframework/functions/fn_initSectors.sqf
  Missionframework/init.sqf
  Missionframework/kp_objectInits.sqf
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/client/misc/resupply_manager.sqf
  Missionframework/scripts/client/misc/stop_renegade.sqf
  Missionframework/scripts/server/CfgFunctions.hpp
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/server/sector/attack_in_progress_fob.sqf
  Missionframework/scripts/server/sector/destroy_fob.sqf
  Missionframework/scripts/server/sector/fn_destroyFob.sqf
  Missionframework/scripts/server/sector/fn_sectorMonitor.fsm
  Missionframework/scripts/server/sector/fn_spawnSectorCrates.sqf
  Missionframework/scripts/server/sector/manage_captureboxes.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/scripts/shared/init_shared.sqf
  Missionframework/scripts/shared/scan_skill.sqf
  Missionframework/scripts/shared/set_skill.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
Labels: enhancement

#764 0.96.7 next fixes
  Missionframework/scripts/server/ai/battlegroup_ai.sqf
  Missionframework/scripts/server/battlegroup/spawn_battlegroup.sqf
Labels: bugfix
