Repository KillahPotatoes/KP-Liberation, pull requests merged in 2020-09, with the labels that each got.

#824 [0.96.7a] GM Preset Updates
  CHANGELOG.md
  Missionframework/arsenal_presets/gm_east.sqf
  Missionframework/arsenal_presets/gm_west.sqf
  Missionframework/kp_liberation_config.sqf
  Missionframework/presets/blufor/gm_east.sqf
  Missionframework/presets/blufor/gm_east_win.sqf
  Missionframework/presets/blufor/gm_west.sqf
  Missionframework/presets/blufor/gm_west_win.sqf
  Missionframework/presets/opfor/gm_east.sqf
  Missionframework/presets/opfor/gm_east_win.sqf
  Missionframework/presets/opfor/gm_west.sqf
  Missionframework/presets/opfor/gm_west_win.sqf
Labels: enhancement

#828 Remove all addons for limited zeus, add param to disable zeus for commander
  CHANGELOG.md
  Missionframework/functions/curator/fn_initCuratorHandlers.sqf
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
Labels: bugfix

#818 V0.96.7a
  .github/workflows/main.yml
  CHANGELOG.md
  Missionframework/CfgFunctions.hpp
  Missionframework/arsenal_presets/gm_east.sqf
  Missionframework/arsenal_presets/gm_west.sqf
  Missionframework/arsenal_presets/vanilla_aaf.sqf
  Missionframework/arsenal_presets/vanilla_csat_ghex.sqf
  Missionframework/arsenal_presets/vanilla_csat_hex.sqf
  Missionframework/arsenal_presets/vanilla_ldf.sqf
  Missionframework/arsenal_presets/vanilla_nato_mtp.sqf
  Missionframework/arsenal_presets/vanilla_nato_tropic.sqf
  Missionframework/arsenal_presets/vanilla_nato_wdl.sqf
  Missionframework/functions/curator/fn_initCuratorHandlers.sqf
  Missionframework/functions/curator/fn_requestZeus.sqf
  Missionframework/functions/fn_addActionsPlayer.sqf
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/functions/ui/fn_overlayUpdateResources.sqf
  Missionframework/init.sqf
  Missionframework/kp_liberation_config.sqf
  Missionframework/onPlayerRespawn.sqf
  Missionframework/presets/blufor/gm_east.sqf
  Missionframework/presets/blufor/gm_east_win.sqf
  Missionframework/presets/blufor/gm_west.sqf
  Missionframework/presets/blufor/gm_west_win.sqf
  Missionframework/presets/opfor/gm_east.sqf
  Missionframework/presets/opfor/gm_east_win.sqf
  Missionframework/presets/opfor/gm_west.sqf
  Missionframework/presets/opfor/gm_west_win.sqf
  Missionframework/presets/opfor/rhs_afrf.sqf
  Missionframework/scripts/client/actions/open_arsenal.sqf
  Missionframework/scripts/client/build/open_build_menu.sqf
  Missionframework/scripts/client/civinformant/civinfo_escort.sqf
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/client/spawn/redeploy_manager.sqf
  Missionframework/scripts/server/ai/prisonner_ai.sqf
  Missionframework/scripts/server/civinformant/civinfo_loop.sqf
  Missionframework/scripts/server/civinformant/tasks/civinfo_task.sqf
  Missionframework/scripts/server/game/apply_default_permissions.sqf
  Missionframework/scripts/server/game/save_manager.sqf
  Missionframework/scripts/server/game/spawn_radio_towers.sqf
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/server/remotecall/build_fob_remote_call.sqf
  Missionframework/scripts/server/remotecall/zeus_remote_call.sqf
  Missionframework/scripts/server/resources/manage_logistics.sqf
  Missionframework/scripts/server/sector/attack_in_progress_fob.sqf
  Missionframework/scripts/server/sector/fn_sectorMonitor.fsm
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/scripts/shared/init_shared.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
Labels: bugfix, enhancement

#832 [v0.96.8] update Italian localization
  Missionframework/stringtable.xml
Labels: enhancement

#834 minor bugfix
  Missionframework/scripts/server/resources/manage_logistics.sqf
Labels: bugfix
