Repository KillahPotatoes/KP-Liberation, pull requests merged in 2020-05, with the labels that each got.

#765 0.96.7 `manage_intel.sqf` as function
  Missionframework/kp_liberation_config.sqf
  Missionframework/presets/init_presets.sqf
  Missionframework/scripts/client/actions/intel_manager.sqf
  Missionframework/scripts/server/CfgFunctions.hpp
  Missionframework/scripts/server/init_server.sqf
  Missionframework/scripts/server/patrols/reinforcements_manager.sqf
  Missionframework/scripts/server/sector/fn_sectorMonitor.fsm
  Missionframework/scripts/server/sector/fn_spawnSectorIntel.sqf
  Missionframework/scripts/server/sector/manage_intel.sqf
Labels: enhancement

#767 0.96.7 More small fixes
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/functions/fn_getSectorOwnership.sqf
  Missionframework/scripts/server/battlegroup/spawn_battlegroup.sqf
  Missionframework/scripts/server/sector/fn_spawnSectorCrates.sqf
Labels: bugfix

#768 0.96.7 Save/Load of sector activation crates
  CHANGELOG.md
  Missionframework/functions/fn_getSaveData.sqf
  Missionframework/scripts/server/game/save_manager.sqf
Labels: enhancement

#770 Add missing semicolon to do_repackage_fob
  Missionframework/scripts/client/actions/do_repackage_fob.sqf
Labels: bugfix

#769 0.96.7 arsenal presets updated
  CHANGELOG.md
  Missionframework/arsenal_presets/3cbBAF.sqf
  Missionframework/arsenal_presets/bwmod.sqf
  Missionframework/arsenal_presets/csat.sqf
  Missionframework/arsenal_presets/killahpotatoes.sqf
  Missionframework/arsenal_presets/rhsusaf.sqf
  Missionframework/arsenal_presets/rhsusaf_ace.sqf
  Missionframework/arsenal_presets/rhsusaf_ace_acre.sqf
  Missionframework/arsenal_presets/sfp.sqf
  Missionframework/arsenal_presets/unsung.sqf
  Missionframework/kp_liberation_config.sqf
  Missionframework/scripts/client/actions/do_repackage_fob.sqf
  Missionframework/scripts/client/init_client.sqf
  _tools/_presets.json
Labels: enhancement

#772 0.96.7 Interactive ingame tutorial
  Missionframework/CfgFunctions.hpp
  Missionframework/description.ext
  Missionframework/scripts/client/CfgFunctions.hpp
  Missionframework/scripts/client/init_client.sqf
  Missionframework/scripts/client/tutorial/CfgTaskDescriptions.hpp
  Missionframework/scripts/client/tutorial/fn_tutorial.fsm
  Missionframework/scripts/server/CfgFunctions.hpp
  Missionframework/scripts/server/base/startgame.sqf
  Missionframework/scripts/shared/fetch_params.sqf
  Missionframework/stringtable.xml
  Missionframework/ui/mission_params.hpp
Labels: enhancement

#773 0.96.7 Exit while on spawnpos search
  Missionframework/functions/fn_spawnRegularSquad.sqf
  Missionframework/functions/fn_spawnVehicle.sqf
  Missionframework/kp_liberation_config.sqf
  Missionframework/scripts/server/sector/fn_spawnSectorCrates.sqf
  Missionframework/scripts/server/sector/fn_spawnSectorIntel.sqf
Labels: bugfix

#776 Block saving if framework not initialized properly
  Missionframework/functions/fn_doSave.sqf
  Missionframework/init.sqf
  Missionframework/presets/init_presets.sqf
Labels: bugfix

#775 Arsenal crate ViV
  CHANGELOG.md
  Missionframework/kp_objectInits.sqf
Labels: enhancement

#774 HUD improvements and optimizations
  CHANGELOG.md
  Missionframework/CfgFunctions.hpp
  Missionframework/functions/fn_getFobResources.sqf
  Missionframework/functions/ui/fn_overlayUpdateResources.sqf
  Missionframework/functions/ui/script_components.hpp
  Missionframework/scripts/client/misc/playerNamespace.sqf
  Missionframework/scripts/client/ui/ui_manager.sqf
  Missionframework/ui/liberation_titles.hpp
Labels: enhancement

#778 Allow recompile in editor and fix typo
  Missionframework/description.ext
  Missionframework/scripts/server/battlegroup/readiness_increase.sqf
Labels: bugfix, enhancement

#777 0.96.7 Tutorial path for conquering first factory
  CHANGELOG.md
  Missionframework/scripts/client/CfgFunctions.hpp
  Missionframework/scripts/client/build/do_sector_build.sqf
  Missionframework/scripts/client/remotecall/remote_call_prisonner.sqf
  Missionframework/scripts/client/tutorial/CfgTaskDescriptions.hpp
  Missionframework/scripts/client/tutorial/fn_handleCrateStorageTask.sqf
  Missionframework/scripts/client/tutorial/fn_handleHealCivTask.sqf
  Missionframework/scripts/client/tutorial/fn_handleTakePowTask.sqf
  Missionframework/scripts/client/tutorial/fn_tutorial.fsm
  Missionframework/scripts/server/ai/prisonner_ai.sqf
  Missionframework/scripts/server/civrep/wounded/civrep_wounded_civs.sqf
  Missionframework/scripts/server/remotecall/sector_liberated_remote_call.sqf
  Missionframework/stringtable.xml
  README.md
Labels: enhancement

#779 0.96.7 hpp cleaning
  .vscode/settings.json
  CHANGELOG.md
  Missionframework/CfgFunctions.hpp
  Missionframework/KP/KPGUI/KPGUI_classes.hpp
  Missionframework/KPLIB_debriefs.hpp
  Missionframework/description.ext
  Missionframework/scripts/client/CfgFunctions.hpp
  Missionframework/scripts/server/CfgFunctions.hpp
  Missionframework/ui/liberation_arsenal.hpp
  Missionframework/ui/liberation_build.hpp
  Missionframework/ui/liberation_deathscreen.hpp
  Missionframework/ui/liberation_deploy.hpp
  Missionframework/ui/liberation_endscreen.hpp
  Missionframework/ui/liberation_halo.hpp
  Missionframework/ui/liberation_logistic.hpp
  Missionframework/ui/liberation_menu.hpp
  Missionframework/ui/liberation_notifications.hpp
  Missionframework/ui/liberation_permissions.hpp
  Missionframework/ui/liberation_production.hpp
  Missionframework/ui/liberation_recycle.hpp
  Missionframework/ui/liberation_repackage_fob.hpp
  Missionframework/ui/liberation_secondary.hpp
  Missionframework/ui/liberation_squad.hpp
  Missionframework/ui/liberation_titles.hpp
  Missionframework/ui/liberation_tutorial.hpp
  Missionframework/ui/mission_params.hpp
  Missionframework/ui/standard_controls.hpp
Labels: enhancement

#793 Aktualizovat soubor stringtable.xml
  CHANGELOG.md
  Missionframework/stringtable.xml
Labels: enhancement

#796 Aktualizovat soubor stringtable.xml
  Missionframework/stringtable.xml
Labels: enhancement

#795 Lower the chance for unarmed BRDM in GM East enemy preset
  CHANGELOG.md
  Missionframework/presets/enemies/gm_east.sqf
Labels: enhancement
